name: payroll
description: To calculate salaries and payslip of employees and workers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5
  ionicons: ^0.2.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  persian_number_utility: ^1.1.3
  flutter_screenutil: ^5.9.0
  logger: ^2.0.2+1
  freezed: ^2.4.2
  #get_it: ^7.6.4
  #dartz: ^0.10.1
  #flutter_keyboard_visibility: ^5.4.1
  #android_intent_plus: ^4.0.2
  #permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir.ttf